
services:
  db:
    image: postgres:15
    restart: always
    container_name: db
    environment:
      - name=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo_db_data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo-network

  odoo:
    build: .
    container_name: odoo
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=odoo
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=odoo
    volumes:
      - odoo_web_data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    ports:
      - "8069:8069"
    networks:
       - odoo-network

volumes:
  odoo_db_data:
  odoo_web_data:

networks:
   odoo-network:
     driver: bridge
