name: Odoo CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # or any other version compatible with your project

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Odoo tests
      env:
        DATABASE_URL: postgresql://odoo:odoo@localhost:5432/odoo
      run: |
        # Replace with your test command
        odoo --db_user=odoo --db_password=odoo --db_host=localhost --db_port=5432 --addons-path=addons -i your_module -d odoo --stop-after-init --test-enable

    - name: Lint Code
      run: |
        pip install flake8
        flake8 your_module
