name: CI Pipeline for Odoo

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get install -y nodejs npm
        sudo apt install python3-pip libldap2-dev libpq-dev libsasl2-dev -y
        python -m pip install --upgrade pip
        pip3 install setuptools wheel
        pip3 install -r requirements.txt
        sudo npm install -g rtlcss

    - name: Lint with pylint
      run: |
        pip install pylint pylint_odoo
        pylint --rcfile=.pylintrc .

    - name: Run tests
      run: |
        pip install pytest
        pytest
        python ./odoo-bin -i account --log-level=test -d minimal_database --test-enable --stop-after-init

    - name: Generate coverage report
      run: |
        pip install pytest-cov
        pytest --cov=odoo tests/

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage/
